# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 340)
        Dialog.setMinimumSize(QtCore.QSize(501, 340))
        Dialog.setMaximumSize(QtCore.QSize(501, 340))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label.setMargin(25)
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">关于本软件</span><br/></p><p><span style=\" font-size:12pt;\">“</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">基于</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:12pt;\">word2vec</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">与聚类模型的同名作者消歧义软件</span><span style=\" font-size:12pt;\">&quot;是一款能</span></p><p><span style=\" font-size:12pt;\">够针对数据库中的文献数据，利用word2vec和聚类模型，对重</span></p><p><span style=\" font-size:12pt;\">名作者进行消歧义的专业数据处理软件。</span><span style=\" font-family:\'宋体\'; font-size:12pt;\">软件小巧快捷，便于</span></p><p><span style=\" font-family:\'宋体\'; font-size:12pt;\">操作。</span></p><p><span style=\" font-family:\'宋体\'; font-size:12pt;\">此软件采用的消歧方法是从文献数据库中论文之间的相似性出</span></p><p><span style=\" font-family:\'宋体\'; font-size:12pt;\">发，建立有偏游走序列，之后使用</span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:12pt;\">word2vec </span><span style=\" font-family:\'宋体\'; font-size:12pt;\">模型进行训练后，</span></p><p><span style=\" font-family:\'宋体\'; font-size:12pt;\">利用聚类方法对同名作者进行区分，达到作者名消歧的目标。</span></p></body></html>"))
