# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 381)
        Dialog.setMinimumSize(QtCore.QSize(501, 381))
        Dialog.setMaximumSize(QtCore.QSize(501, 381))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">关于本软件</span><br/></p><p><span style=\" font-size:12pt;\">  “基于Word2vec模型与神经网络同名作者消歧义软件”是</span></p><p><span style=\" font-size:12pt;\">一款能有效从文献数据库中大量同名作者之间区分各个单独作</span></p><p><span style=\" font-size:12pt;\">者及他们所写的论文的软件。软件小巧便于操作。</span></p><p><span style=\" font-size:12pt;\"><br/>  此软件采用的消歧方法是根据数据库中各个论文的相似度</span></p><p><span style=\" font-size:12pt;\">构建相似度矩阵，并基于Word2vec方法得到每篇文章的嵌入向</span></p><p><span style=\" font-size:12pt;\">量，之后利用多层感知机模型区分同名作者。该方法在DBLP数</span></p><p><span style=\" font-size:12pt;\">据库中对两百多位同名作者进行了实验，证明该方法消歧效果</span></p><p><span style=\" font-size:12pt;\">优越。</span><br/></p></body></html>"))
